language: python
python:
  - "3.6"
before_install:
  - openssl aes-256-cbc -K $encrypted_8c00ff17400c_key -iv $encrypted_8c00ff17400c_iv -in ../flask.cfg.enc -out instance/flask.cfg -d
install:
  - pip install -r requirements.txt
script:
  - pytest tests --doctest-modules  -v --cov api --cov-report term-missing
after_success:
  - coveralls